version: "3.8"
services:
  backend:
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
