version: "3.8"
services:
  backend:
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
