version: "3.8"
services:
  backend:
    build: ./BACKEND
    ports:
      - "8000:8000"
    volumes:
      - ./BACKEND:/app
    env_file:
      - ./BACKEND/.env
  frontend:
    build: ./
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
